export const colors = {
  background: '#FFFFFF',
  screenGray: '#FAFAFA',
  black: '#111111',
  darkGray: '#2B2B2B',
  mediumGray: '#8A8A8E',
  lightGray: '#C7C7CC',
  divider: '#EBEBEB',
  chipBackground: '#F2F2F3',
  cardBackground: '#F5F5F5',
  warningBackground: '#FDF3E7',
  warningIcon: '#E8A33D',
  infoBackground: '#EAF3FB',
  infoIcon: '#4A9FE0',
  red: '#D6291F',
  white: '#FFFFFF',
  mapBackground: '#E9ECE7',
  star: '#111111',
} as const;
